name: ci
on: [push, pull_request]
jobs:
  qa:
    name: Quality Assurance
    uses: ./.github/workflows/fun-quality-assurance.yml
  versioning:
    name: Versioning
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      deploy: ${{ steps.version.outputs.deploy }}
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: telenornorway/action-versioning@v0.1.10
        id: version
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          strategy: commit
          value: ${{ github.event.head_commit.message }}
  build:
    name: Build
    uses: ./.github/workflows/fun-build.yml
    if: needs.versioning.outputs.deploy == 'yes'
    needs: [versioning]
    permissions:
      contents: write
    with:
      version: ${{ needs.versioning.outputs.version }}
  release:
    name: Release
    uses: ./.github/workflows/fun-release.yml
    needs: [qa, versioning, build]
    permissions:
      contents: write
    with:
      deploy: ${{ needs.versioning.outputs.deploy }}
      version: ${{ needs.versioning.outputs.version }}
      title: Release v${{ needs.versioning.outputs.version }}
