name: ci
on: [push, pull_request]
permissions:
  contents: write
jobs:
  qa:
    uses: ./.github/workflows/fun-quality-assurance.yml
  versioning:
    name: Versioning
    if: github.event_name == 'push'
    uses: ./.github/workflows/fun-versioning.yml
    with:
      strategy: commit
      input: ${{ github.event.head_commit.message }}
  build:
    name: Build
    needs: [versioning]
    if: needs.versioning.outputs.deploy == 'yes'
    uses: ./.github/workflows/fun-build.yml
    with:
      version: ${{ needs.versioning.outputs.version }}
  release:
    name: Release
    needs: [qa, versioning, build]
    uses: ./.github/workflows/fun-release.yml
    with:
      deploy: ${{ needs.versioning.outputs.deploy }}
      version: ${{ needs.versioning.outputs.version }}
      title: Release v${{ needs.versioning.outputs.version }}
