name: ci
on: [push, pull_request]
jobs:
  qa:
    name: Quality Assurance
    uses: ./.github/workflows/fun-quality-assurance.yml
  versioning:
    name: Versioning
    uses: ./.github/workflows/fun-versioning.yml
    if: github.event_name == 'push'
    with:
      strategy: commit
      input: ${{ github.event.head_commit.message }}
  test:
    name: Test
    needs: [versioning]
    runs-on: ubuntu-latest
    steps:
      - run: echo "$deploy $version"
        env:
          deploy: ${{ needs.versioning.outputs.deploy }}
          version: ${{ needs.versioning.outputs.version }}
  build:
    name: Build
    uses: ./.github/workflows/fun-build.yml
    if: needs.versioning.outputs.deploy == 'yes'
    needs: [versioning]
    permissions:
      contents: write
    with:
      version: ${{ needs.versioning.outputs.version }}
  release:
    name: Release
    uses: ./.github/workflows/fun-release.yml
    needs: [qa, versioning, build]
    permissions:
      contents: write
    with:
      deploy: ${{ needs.versioning.outputs.deploy }}
      version: ${{ needs.versioning.outputs.version }}
      title: Release v${{ needs.versioning.outputs.version }}
