name: Start release
on:
  workflow_dispatch:
    inputs:
      releaseKind:
        description: Kind of release
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
        required: true
      releaseMessage:
        description: The message to put in the release
        type: string
        required: false
jobs:
  qa:
    uses: ./.github/workflows/fun-quality-assurance.yml
    if: github.ref == 'refs/heads/main'
  versioning:
    name: Versioning
    uses: ./.github/workflows/fun-versioning.yml
    if: github.ref == 'refs/heads/main'
    with:
      strategy: semver
      input: ${{ inputs.releaseKind }}
  build:
    name: Build
    uses: ./.github/workflows/fun-build.yml
    if: needs.versioning.outputs.deploy == 'yes'
    needs: [versioning]
    permissions:
      contents: write
    with:
      version: ${{ needs.versioning.outputs.version }}
  release:
    name: Release
    uses: ./.github/workflows/fun-release.yml
    needs: [qa, versioning, build]
    permissions:
      contents: write
    with:
      deploy: ${{ needs.versioning.outputs.deploy }}
      version: ${{ needs.versioning.outputs.version }}
      title: |
        ${{ inputs.releaseMessage || format('Release v{0}', needs.versioning.outputs.version) }}
